apiVersion: v1
data:
  grafana.ini: |
    [server]
    domain = grafana.cloudfiftytwo.com
    root_url = https://grafana.cloudfiftytwo.com
    [analytics]
    reporting_enabled = false
    check_for_updates = false
    [security]
    admin_user = admin
    [auth.generic_oauth]
    name = Keycloak
    enabled = true
    allow_sign_up = true
    client_id = grafana
    client_secret = 12wedfvghyu890olmjhgtr43erfghjki8765
    scopes = openid profile email
    auth_url = https://keycloak-rad.cloudfiftytwo.com/realms/cloudfiftytwo/protocol/openid-connect/auth
    token_url = https://keycloak-rad.cloudfiftytwo.com/realms/cloudfiftytwo/protocol/openid-connect/token
    api_url = https://keycloak-rad.cloudfiftytwo.com/realms/cloudfiftytwo/protocol/openid-connect/userinfo
    role_attribute_path = contains(roles[*], 'grafana-admin') && 'Admin' || contains(roles[*], 'grafana-editor') && 'Editor' || 'Viewer'
immutable: false
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-17T13:21:18Z"
  name: grafana-config
  namespace: grafana
  resourceVersion: "48424"
  uid: 25e2a8a2-ddc1-4cb5-ab16-b602834b8b07
