apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-oauth-config
  namespace: grafana
data:
  oauth.ini: |
    [auth.generic_oauth]
    enabled = true
    name = Keycloak
    allow_sign_up = true
    client_id = grafana
    client_secret = 12wedfvghyu890olmjhgtr43erfghjki8765
    scopes = openid profile email
    auth_url = https://keycloak-rad.cloudfiftytwo.com/realms/cloudfiftytwo/protocol/openid-connect/auth
    token_url = https://keycloak-rad.cloudfiftytwo.com/realms/cloudfiftytwo/protocol/openid-connect/token
    api_url = https://keycloak-rad.cloudfiftytwo.com/realms/cloudfiftytwo/protocol/openid-connect/token
    login_attribute_path = preferred_username
    use_pkce = true
    
    # Group mapping
    role_attribute_path = contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'
    
    [auth]
    oauth_auto_login = false
    disable_login_form = false
    
    [security]
    oauth_auto_login = false
    disable_initial_admin_creation = false
    
    [users]
    auto_assign_org_role = Viewer
    
    [server]
    root_url = https://grafana.cloudfiftytwo.com
